use std::convert::TryInto;
use super::belt::*;
use super::belt_codes::*;
use super::belt_meta::*;
use super::config::*;
use super::port::*;

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum BeltType {
  /*
  Generated with:

  let i = 0;
  let codes = [];
  let ports = ['n', 'i', 'o', 'u'];
  for (const u of ports) {
      for (const r of ports) {
          for (const d of ports) {
              for (const l of ports) {
                  let ins = [];
                  let outs = [];
                  let uus = [];
                  if (u === 'i') ins.push('u');
                  if (u === 'o') outs.push('u');
                  if (u === 'u') uus.push('u');
                  if (r === 'i') ins.push('r');
                  if (r === 'o') outs.push('r');
                  if (r === 'u') uus.push('r');
                  if (d === 'i') ins.push('d');
                  if (d === 'o') outs.push('d');
                  if (d === 'u') uus.push('d');
                  if (l === 'i') ins.push('l');
                  if (l === 'o') outs.push('l');
                  if (l === 'u') uus.push('l');
                  codes.push(`${`${ins.join('')}_${outs.join('')}${uus.length?'_':''}${uus.join('')}`.toUpperCase()} = ${i++},`);
              }
          }
      }
  }
  console.log(codes.join('\n'))
  */

  NONE = CONFIG_NODE_BELT_NONE as isize,
  UNKNOWN = CONFIG_NODE_BELT_UNKNOWN as isize,
  INVALID = CONFIG_NODE_BELT_INVALID as isize,
  L_ = CONFIG_NODE_BELT_L_ as isize,
  _L = CONFIG_NODE_BELT__L as isize,
  __L = CONFIG_NODE_BELT___L as isize,
  D_ = CONFIG_NODE_BELT_D_ as isize,
  DL_ = CONFIG_NODE_BELT_DL_ as isize,
  D_L = CONFIG_NODE_BELT_D_L as isize,
  D__L = CONFIG_NODE_BELT_D__L as isize,
  _D = CONFIG_NODE_BELT__D as isize,
  L_D = CONFIG_NODE_BELT_L_D as isize,
  _DL = CONFIG_NODE_BELT__DL as isize,
  _D_L = CONFIG_NODE_BELT__D_L as isize,
  __D = CONFIG_NODE_BELT___D as isize,
  L__D = CONFIG_NODE_BELT_L__D as isize,
  _L_D = CONFIG_NODE_BELT__L_D as isize,
  __DL = CONFIG_NODE_BELT___DL as isize,
  R_ = CONFIG_NODE_BELT_R_ as isize,
  LR_ = CONFIG_NODE_BELT_LR_ as isize,
  R_L = CONFIG_NODE_BELT_R_L as isize,
  R__L = CONFIG_NODE_BELT_R__L as isize,
  DR_ = CONFIG_NODE_BELT_DR_ as isize,
  DLR_ = CONFIG_NODE_BELT_DLR_ as isize,
  DR_L = CONFIG_NODE_BELT_DR_L as isize,
  DR__L = CONFIG_NODE_BELT_DR__L as isize,
  R_D = CONFIG_NODE_BELT_R_D as isize,
  LR_D = CONFIG_NODE_BELT_LR_D as isize,
  R_DL = CONFIG_NODE_BELT_R_DL as isize,
  R_D_L = CONFIG_NODE_BELT_R_D_L as isize,
  R__D = CONFIG_NODE_BELT_R__D as isize,
  LR__D = CONFIG_NODE_BELT_LR__D as isize,
  R_L_D = CONFIG_NODE_BELT_R_L_D as isize,
  R__DL = CONFIG_NODE_BELT_R__DL as isize,
  _R = CONFIG_NODE_BELT__R as isize,
  L_R = CONFIG_NODE_BELT_L_R as isize,
  _LR = CONFIG_NODE_BELT__LR as isize,
  _R_L = CONFIG_NODE_BELT__R_L as isize,
  D_R = CONFIG_NODE_BELT_D_R as isize,
  DL_R = CONFIG_NODE_BELT_DL_R as isize,
  D_LR = CONFIG_NODE_BELT_D_LR as isize,
  D_R_L = CONFIG_NODE_BELT_D_R_L as isize,
  _DR = CONFIG_NODE_BELT__DR as isize,
  L_DR = CONFIG_NODE_BELT_L_DR as isize,
  _DLR = CONFIG_NODE_BELT__DLR as isize,
  _DR_L = CONFIG_NODE_BELT__DR_L as isize,
  _R_D = CONFIG_NODE_BELT__R_D as isize,
  L_R_D = CONFIG_NODE_BELT_L_R_D as isize,
  _LR_D = CONFIG_NODE_BELT__LR_D as isize,
  _R_DL = CONFIG_NODE_BELT__R_DL as isize,
  __R = CONFIG_NODE_BELT___R as isize,
  L__R = CONFIG_NODE_BELT_L__R as isize,
  _L_R = CONFIG_NODE_BELT__L_R as isize,
  __LR = CONFIG_NODE_BELT___LR as isize,
  D__R = CONFIG_NODE_BELT_D__R as isize,
  DL__R = CONFIG_NODE_BELT_DL__R as isize,
  D_L_R = CONFIG_NODE_BELT_D_L_R as isize,
  D__LR = CONFIG_NODE_BELT_D__LR as isize,
  _D_R = CONFIG_NODE_BELT__D_R as isize,
  L_D_R = CONFIG_NODE_BELT_L_D_R as isize,
  _DL_R = CONFIG_NODE_BELT__DL_R as isize,
  _D_LR = CONFIG_NODE_BELT__D_LR as isize,
  __DR = CONFIG_NODE_BELT___DR as isize,
  L__DR = CONFIG_NODE_BELT_L__DR as isize,
  _L_DR = CONFIG_NODE_BELT__L_DR as isize,
  __DLR = CONFIG_NODE_BELT___DLR as isize,
  U_ = CONFIG_NODE_BELT_U_ as isize,
  LU_ = CONFIG_NODE_BELT_LU_ as isize,
  U_L = CONFIG_NODE_BELT_U_L as isize,
  U__L = CONFIG_NODE_BELT_U__L as isize,
  DU_ = CONFIG_NODE_BELT_DU_ as isize,
  DLU_ = CONFIG_NODE_BELT_DLU_ as isize,
  DU_L = CONFIG_NODE_BELT_DU_L as isize,
  DU__L = CONFIG_NODE_BELT_DU__L as isize,
  U_D = CONFIG_NODE_BELT_U_D as isize,
  LU_D = CONFIG_NODE_BELT_LU_D as isize,
  U_DL = CONFIG_NODE_BELT_U_DL as isize,
  U_D_L = CONFIG_NODE_BELT_U_D_L as isize,
  U__D = CONFIG_NODE_BELT_U__D as isize,
  LU__D = CONFIG_NODE_BELT_LU__D as isize,
  U_L_D = CONFIG_NODE_BELT_U_L_D as isize,
  U__DL = CONFIG_NODE_BELT_U__DL as isize,
  RU_ = CONFIG_NODE_BELT_RU_ as isize,
  LRU_ = CONFIG_NODE_BELT_LRU_ as isize,
  RU_L = CONFIG_NODE_BELT_RU_L as isize,
  RU__L = CONFIG_NODE_BELT_RU__L as isize,
  DRU_ = CONFIG_NODE_BELT_DRU_ as isize,
  DLRU_ = CONFIG_NODE_BELT_DLRU_ as isize,
  DRU_L = CONFIG_NODE_BELT_DRU_L as isize,
  DRU__L = CONFIG_NODE_BELT_DRU__L as isize,
  RU_D = CONFIG_NODE_BELT_RU_D as isize,
  LRU_D = CONFIG_NODE_BELT_LRU_D as isize,
  RU_DL = CONFIG_NODE_BELT_RU_DL as isize,
  RU_D_L = CONFIG_NODE_BELT_RU_D_L as isize,
  RU__D = CONFIG_NODE_BELT_RU__D as isize,
  LRU__D = CONFIG_NODE_BELT_LRU__D as isize,
  RU_L_D = CONFIG_NODE_BELT_RU_L_D as isize,
  RU__DL = CONFIG_NODE_BELT_RU__DL as isize,
  U_R = CONFIG_NODE_BELT_U_R as isize,
  LU_R = CONFIG_NODE_BELT_LU_R as isize,
  U_LR = CONFIG_NODE_BELT_U_LR as isize,
  U_R_L = CONFIG_NODE_BELT_U_R_L as isize,
  DU_R = CONFIG_NODE_BELT_DU_R as isize,
  DLU_R = CONFIG_NODE_BELT_DLU_R as isize,
  DU_LR = CONFIG_NODE_BELT_DU_LR as isize,
  DU_R_L = CONFIG_NODE_BELT_DU_R_L as isize,
  U_DR = CONFIG_NODE_BELT_U_DR as isize,
  LU_DR = CONFIG_NODE_BELT_LU_DR as isize,
  U_DLR = CONFIG_NODE_BELT_U_DLR as isize,
  U_DR_L = CONFIG_NODE_BELT_U_DR_L as isize,
  U_R_D = CONFIG_NODE_BELT_U_R_D as isize,
  LU_R_D = CONFIG_NODE_BELT_LU_R_D as isize,
  U_LR_D = CONFIG_NODE_BELT_U_LR_D as isize,
  U_R_DL = CONFIG_NODE_BELT_U_R_DL as isize,
  U__R = CONFIG_NODE_BELT_U__R as isize,
  LU__R = CONFIG_NODE_BELT_LU__R as isize,
  U_L_R = CONFIG_NODE_BELT_U_L_R as isize,
  U__LR = CONFIG_NODE_BELT_U__LR as isize,
  DU__R = CONFIG_NODE_BELT_DU__R as isize,
  DLU__R = CONFIG_NODE_BELT_DLU__R as isize,
  DU_L_R = CONFIG_NODE_BELT_DU_L_R as isize,
  DU__LR = CONFIG_NODE_BELT_DU__LR as isize,
  U_D_R = CONFIG_NODE_BELT_U_D_R as isize,
  LU_D_R = CONFIG_NODE_BELT_LU_D_R as isize,
  U_DL_R = CONFIG_NODE_BELT_U_DL_R as isize,
  U_D_LR = CONFIG_NODE_BELT_U_D_LR as isize,
  U__DR = CONFIG_NODE_BELT_U__DR as isize,
  LU__DR = CONFIG_NODE_BELT_LU__DR as isize,
  U_L_DR = CONFIG_NODE_BELT_U_L_DR as isize,
  U__DLR = CONFIG_NODE_BELT_U__DLR as isize,
  _U = CONFIG_NODE_BELT__U as isize,
  L_U = CONFIG_NODE_BELT_L_U as isize,
  _LU = CONFIG_NODE_BELT__LU as isize,
  _U_L = CONFIG_NODE_BELT__U_L as isize,
  D_U = CONFIG_NODE_BELT_D_U as isize,
  DL_U = CONFIG_NODE_BELT_DL_U as isize,
  D_LU = CONFIG_NODE_BELT_D_LU as isize,
  D_U_L = CONFIG_NODE_BELT_D_U_L as isize,
  _DU = CONFIG_NODE_BELT__DU as isize,
  L_DU = CONFIG_NODE_BELT_L_DU as isize,
  _DLU = CONFIG_NODE_BELT__DLU as isize,
  _DU_L = CONFIG_NODE_BELT__DU_L as isize,
  _U_D = CONFIG_NODE_BELT__U_D as isize,
  L_U_D = CONFIG_NODE_BELT_L_U_D as isize,
  _LU_D = CONFIG_NODE_BELT__LU_D as isize,
  _U_DL = CONFIG_NODE_BELT__U_DL as isize,
  R_U = CONFIG_NODE_BELT_R_U as isize,
  LR_U = CONFIG_NODE_BELT_LR_U as isize,
  R_LU = CONFIG_NODE_BELT_R_LU as isize,
  R_U_L = CONFIG_NODE_BELT_R_U_L as isize,
  DR_U = CONFIG_NODE_BELT_DR_U as isize,
  DLR_U = CONFIG_NODE_BELT_DLR_U as isize,
  DR_LU = CONFIG_NODE_BELT_DR_LU as isize,
  DR_U_L = CONFIG_NODE_BELT_DR_U_L as isize,
  R_DU = CONFIG_NODE_BELT_R_DU as isize,
  LR_DU = CONFIG_NODE_BELT_LR_DU as isize,
  R_DLU = CONFIG_NODE_BELT_R_DLU as isize,
  R_DU_L = CONFIG_NODE_BELT_R_DU_L as isize,
  R_U_D = CONFIG_NODE_BELT_R_U_D as isize,
  LR_U_D = CONFIG_NODE_BELT_LR_U_D as isize,
  R_LU_D = CONFIG_NODE_BELT_R_LU_D as isize,
  R_U_DL = CONFIG_NODE_BELT_R_U_DL as isize,
  _RU = CONFIG_NODE_BELT__RU as isize,
  L_RU = CONFIG_NODE_BELT_L_RU as isize,
  _LRU = CONFIG_NODE_BELT__LRU as isize,
  _RU_L = CONFIG_NODE_BELT__RU_L as isize,
  D_RU = CONFIG_NODE_BELT_D_RU as isize,
  DL_RU = CONFIG_NODE_BELT_DL_RU as isize,
  D_LRU = CONFIG_NODE_BELT_D_LRU as isize,
  D_RU_L = CONFIG_NODE_BELT_D_RU_L as isize,
  _DRU = CONFIG_NODE_BELT__DRU as isize,
  L_DRU = CONFIG_NODE_BELT_L_DRU as isize,
  _DLRU = CONFIG_NODE_BELT__DLRU as isize,
  _DRU_L = CONFIG_NODE_BELT__DRU_L as isize,
  _RU_D = CONFIG_NODE_BELT__RU_D as isize,
  L_RU_D = CONFIG_NODE_BELT_L_RU_D as isize,
  _LRU_D = CONFIG_NODE_BELT__LRU_D as isize,
  _RU_DL = CONFIG_NODE_BELT__RU_DL as isize,
  _U_R = CONFIG_NODE_BELT__U_R as isize,
  L_U_R = CONFIG_NODE_BELT_L_U_R as isize,
  _LU_R = CONFIG_NODE_BELT__LU_R as isize,
  _U_LR = CONFIG_NODE_BELT__U_LR as isize,
  D_U_R = CONFIG_NODE_BELT_D_U_R as isize,
  DL_U_R = CONFIG_NODE_BELT_DL_U_R as isize,
  D_LU_R = CONFIG_NODE_BELT_D_LU_R as isize,
  D_U_LR = CONFIG_NODE_BELT_D_U_LR as isize,
  _DU_R = CONFIG_NODE_BELT__DU_R as isize,
  L_DU_R = CONFIG_NODE_BELT_L_DU_R as isize,
  _DLU_R = CONFIG_NODE_BELT__DLU_R as isize,
  _DU_LR = CONFIG_NODE_BELT__DU_LR as isize,
  _U_DR = CONFIG_NODE_BELT__U_DR as isize,
  L_U_DR = CONFIG_NODE_BELT_L_U_DR as isize,
  _LU_DR = CONFIG_NODE_BELT__LU_DR as isize,
  _U_DLR = CONFIG_NODE_BELT__U_DLR as isize,
  __U = CONFIG_NODE_BELT___U as isize,
  L__U = CONFIG_NODE_BELT_L__U as isize,
  _L_U = CONFIG_NODE_BELT__L_U as isize,
  __LU = CONFIG_NODE_BELT___LU as isize,
  D__U = CONFIG_NODE_BELT_D__U as isize,
  DL__U = CONFIG_NODE_BELT_DL__U as isize,
  D_L_U = CONFIG_NODE_BELT_D_L_U as isize,
  D__LU = CONFIG_NODE_BELT_D__LU as isize,
  _D_U = CONFIG_NODE_BELT__D_U as isize,
  L_D_U = CONFIG_NODE_BELT_L_D_U as isize,
  _DL_U = CONFIG_NODE_BELT__DL_U as isize,
  _D_LU = CONFIG_NODE_BELT__D_LU as isize,
  __DU = CONFIG_NODE_BELT___DU as isize,
  L__DU = CONFIG_NODE_BELT_L__DU as isize,
  _L_DU = CONFIG_NODE_BELT__L_DU as isize,
  __DLU = CONFIG_NODE_BELT___DLU as isize,
  R__U = CONFIG_NODE_BELT_R__U as isize,
  LR__U = CONFIG_NODE_BELT_LR__U as isize,
  R_L_U = CONFIG_NODE_BELT_R_L_U as isize,
  R__LU = CONFIG_NODE_BELT_R__LU as isize,
  DR__U = CONFIG_NODE_BELT_DR__U as isize,
  DLR__U = CONFIG_NODE_BELT_DLR__U as isize,
  DR_L_U = CONFIG_NODE_BELT_DR_L_U as isize,
  DR__LU = CONFIG_NODE_BELT_DR__LU as isize,
  R_D_U = CONFIG_NODE_BELT_R_D_U as isize,
  LR_D_U = CONFIG_NODE_BELT_LR_D_U as isize,
  R_DL_U = CONFIG_NODE_BELT_R_DL_U as isize,
  R_D_LU = CONFIG_NODE_BELT_R_D_LU as isize,
  R__DU = CONFIG_NODE_BELT_R__DU as isize,
  LR__DU = CONFIG_NODE_BELT_LR__DU as isize,
  R_L_DU = CONFIG_NODE_BELT_R_L_DU as isize,
  R__DLU = CONFIG_NODE_BELT_R__DLU as isize,
  _R_U = CONFIG_NODE_BELT__R_U as isize,
  L_R_U = CONFIG_NODE_BELT_L_R_U as isize,
  _LR_U = CONFIG_NODE_BELT__LR_U as isize,
  _R_LU = CONFIG_NODE_BELT__R_LU as isize,
  D_R_U = CONFIG_NODE_BELT_D_R_U as isize,
  DL_R_U = CONFIG_NODE_BELT_DL_R_U as isize,
  D_LR_U = CONFIG_NODE_BELT_D_LR_U as isize,
  D_R_LU = CONFIG_NODE_BELT_D_R_LU as isize,
  _DR_U = CONFIG_NODE_BELT__DR_U as isize,
  L_DR_U = CONFIG_NODE_BELT_L_DR_U as isize,
  _DLR_U = CONFIG_NODE_BELT__DLR_U as isize,
  _DR_LU = CONFIG_NODE_BELT__DR_LU as isize,
  _R_DU = CONFIG_NODE_BELT__R_DU as isize,
  L_R_DU = CONFIG_NODE_BELT_L_R_DU as isize,
  _LR_DU = CONFIG_NODE_BELT__LR_DU as isize,
  _R_DLU = CONFIG_NODE_BELT__R_DLU as isize,
  __RU = CONFIG_NODE_BELT___RU as isize,
  L__RU = CONFIG_NODE_BELT_L__RU as isize,
  _L_RU = CONFIG_NODE_BELT__L_RU as isize,
  __LRU = CONFIG_NODE_BELT___LRU as isize,
  D__RU = CONFIG_NODE_BELT_D__RU as isize,
  DL__RU = CONFIG_NODE_BELT_DL__RU as isize,
  D_L_RU = CONFIG_NODE_BELT_D_L_RU as isize,
  D__LRU = CONFIG_NODE_BELT_D__LRU as isize,
  _D_RU = CONFIG_NODE_BELT__D_RU as isize,
  L_D_RU = CONFIG_NODE_BELT_L_D_RU as isize,
  _DL_RU = CONFIG_NODE_BELT__DL_RU as isize,
  _D_LRU = CONFIG_NODE_BELT__D_LRU as isize,
  __DRU = CONFIG_NODE_BELT___DRU as isize,
  L__DRU = CONFIG_NODE_BELT_L__DRU as isize,
  _L_DRU = CONFIG_NODE_BELT__L_DRU as isize,
  __DLRU = CONFIG_NODE_BELT___DLRU as isize, // Keep last item
}
// Keep in sync...
pub const BELT_TYPE_COUNT: usize = (BeltType::INVALID as usize) + 1;

// Naming _is_ hard
pub const BELT_TYPES_NOT_INDEXABLE_BY_TYPE_BUT_BY_CODE_POS: [BeltType; 258] = [
  BeltType::NONE,
  BeltType::UNKNOWN,
  BeltType::INVALID,
  BeltType::L_,
  BeltType::_L,
  BeltType::__L,
  BeltType::D_,
  BeltType::DL_,
  BeltType::D_L,
  BeltType::D__L,
  BeltType::_D,
  BeltType::L_D,
  BeltType::_DL,
  BeltType::_D_L,
  BeltType::__D,
  BeltType::L__D,
  BeltType::_L_D,
  BeltType::__DL,
  BeltType::R_,
  BeltType::LR_,
  BeltType::R_L,
  BeltType::R__L,
  BeltType::DR_,
  BeltType::DLR_,
  BeltType::DR_L,
  BeltType::DR__L,
  BeltType::R_D,
  BeltType::LR_D,
  BeltType::R_DL,
  BeltType::R_D_L,
  BeltType::R__D,
  BeltType::LR__D,
  BeltType::R_L_D,
  BeltType::R__DL,
  BeltType::_R,
  BeltType::L_R,
  BeltType::_LR,
  BeltType::_R_L,
  BeltType::D_R,
  BeltType::DL_R,
  BeltType::D_LR,
  BeltType::D_R_L,
  BeltType::_DR,
  BeltType::L_DR,
  BeltType::_DLR,
  BeltType::_DR_L,
  BeltType::_R_D,
  BeltType::L_R_D,
  BeltType::_LR_D,
  BeltType::_R_DL,
  BeltType::__R,
  BeltType::L__R,
  BeltType::_L_R,
  BeltType::__LR,
  BeltType::D__R,
  BeltType::DL__R,
  BeltType::D_L_R,
  BeltType::D__LR,
  BeltType::_D_R,
  BeltType::L_D_R,
  BeltType::_DL_R,
  BeltType::_D_LR,
  BeltType::__DR,
  BeltType::L__DR,
  BeltType::_L_DR,
  BeltType::__DLR,
  BeltType::U_,
  BeltType::LU_,
  BeltType::U_L,
  BeltType::U__L,
  BeltType::DU_,
  BeltType::DLU_,
  BeltType::DU_L,
  BeltType::DU__L,
  BeltType::U_D,
  BeltType::LU_D,
  BeltType::U_DL,
  BeltType::U_D_L,
  BeltType::U__D,
  BeltType::LU__D,
  BeltType::U_L_D,
  BeltType::U__DL,
  BeltType::RU_,
  BeltType::LRU_,
  BeltType::RU_L,
  BeltType::RU__L,
  BeltType::DRU_,
  BeltType::DLRU_,
  BeltType::DRU_L,
  BeltType::DRU__L,
  BeltType::RU_D,
  BeltType::LRU_D,
  BeltType::RU_DL,
  BeltType::RU_D_L,
  BeltType::RU__D,
  BeltType::LRU__D,
  BeltType::RU_L_D,
  BeltType::RU__DL,
  BeltType::U_R,
  BeltType::LU_R,
  BeltType::U_LR,
  BeltType::U_R_L,
  BeltType::DU_R,
  BeltType::DLU_R,
  BeltType::DU_LR,
  BeltType::DU_R_L,
  BeltType::U_DR,
  BeltType::LU_DR,
  BeltType::U_DLR,
  BeltType::U_DR_L,
  BeltType::U_R_D,
  BeltType::LU_R_D,
  BeltType::U_LR_D,
  BeltType::U_R_DL,
  BeltType::U__R,
  BeltType::LU__R,
  BeltType::U_L_R,
  BeltType::U__LR,
  BeltType::DU__R,
  BeltType::DLU__R,
  BeltType::DU_L_R,
  BeltType::DU__LR,
  BeltType::U_D_R,
  BeltType::LU_D_R,
  BeltType::U_DL_R,
  BeltType::U_D_LR,
  BeltType::U__DR,
  BeltType::LU__DR,
  BeltType::U_L_DR,
  BeltType::U__DLR,
  BeltType::_U,
  BeltType::L_U,
  BeltType::_LU,
  BeltType::_U_L,
  BeltType::D_U,
  BeltType::DL_U,
  BeltType::D_LU,
  BeltType::D_U_L,
  BeltType::_DU,
  BeltType::L_DU,
  BeltType::_DLU,
  BeltType::_DU_L,
  BeltType::_U_D,
  BeltType::L_U_D,
  BeltType::_LU_D,
  BeltType::_U_DL,
  BeltType::R_U,
  BeltType::LR_U,
  BeltType::R_LU,
  BeltType::R_U_L,
  BeltType::DR_U,
  BeltType::DLR_U,
  BeltType::DR_LU,
  BeltType::DR_U_L,
  BeltType::R_DU,
  BeltType::LR_DU,
  BeltType::R_DLU,
  BeltType::R_DU_L,
  BeltType::R_U_D,
  BeltType::LR_U_D,
  BeltType::R_LU_D,
  BeltType::R_U_DL,
  BeltType::_RU,
  BeltType::L_RU,
  BeltType::_LRU,
  BeltType::_RU_L,
  BeltType::D_RU,
  BeltType::DL_RU,
  BeltType::D_LRU,
  BeltType::D_RU_L,
  BeltType::_DRU,
  BeltType::L_DRU,
  BeltType::_DLRU,
  BeltType::_DRU_L,
  BeltType::_RU_D,
  BeltType::L_RU_D,
  BeltType::_LRU_D,
  BeltType::_RU_DL,
  BeltType::_U_R,
  BeltType::L_U_R,
  BeltType::_LU_R,
  BeltType::_U_LR,
  BeltType::D_U_R,
  BeltType::DL_U_R,
  BeltType::D_LU_R,
  BeltType::D_U_LR,
  BeltType::_DU_R,
  BeltType::L_DU_R,
  BeltType::_DLU_R,
  BeltType::_DU_LR,
  BeltType::_U_DR,
  BeltType::L_U_DR,
  BeltType::_LU_DR,
  BeltType::_U_DLR,
  BeltType::__U,
  BeltType::L__U,
  BeltType::_L_U,
  BeltType::__LU,
  BeltType::D__U,
  BeltType::DL__U,
  BeltType::D_L_U,
  BeltType::D__LU,
  BeltType::_D_U,
  BeltType::L_D_U,
  BeltType::_DL_U,
  BeltType::_D_LU,
  BeltType::__DU,
  BeltType::L__DU,
  BeltType::_L_DU,
  BeltType::__DLU,
  BeltType::R__U,
  BeltType::LR__U,
  BeltType::R_L_U,
  BeltType::R__LU,
  BeltType::DR__U,
  BeltType::DLR__U,
  BeltType::DR_L_U,
  BeltType::DR__LU,
  BeltType::R_D_U,
  BeltType::LR_D_U,
  BeltType::R_DL_U,
  BeltType::R_D_LU,
  BeltType::R__DU,
  BeltType::LR__DU,
  BeltType::R_L_DU,
  BeltType::R__DLU,
  BeltType::_R_U,
  BeltType::L_R_U,
  BeltType::_LR_U,
  BeltType::_R_LU,
  BeltType::D_R_U,
  BeltType::DL_R_U,
  BeltType::D_LR_U,
  BeltType::D_R_LU,
  BeltType::_DR_U,
  BeltType::L_DR_U,
  BeltType::_DLR_U,
  BeltType::_DR_LU,
  BeltType::_R_DU,
  BeltType::L_R_DU,
  BeltType::_LR_DU,
  BeltType::_R_DLU,
  BeltType::__RU,
  BeltType::L__RU,
  BeltType::_L_RU,
  BeltType::__LRU,
  BeltType::D__RU,
  BeltType::DL__RU,
  BeltType::D_L_RU,
  BeltType::D__LRU,
  BeltType::_D_RU,
  BeltType::L_D_RU,
  BeltType::_DL_RU,
  BeltType::_D_LRU,
  BeltType::__DRU,
  BeltType::L__DRU,
  BeltType::_L_DRU,
  BeltType::__DLRU,
];

pub fn belt_type_to_belt_meta(belt_type: BeltType) -> BeltMeta {
  return match belt_type {
    BeltType::NONE => BELT_NONE,
    BeltType::UNKNOWN => BELT_UNKNOWN,
    BeltType::INVALID => BELT_INVALID,
    BeltType::L_ => BELT_L_,
    BeltType::_L => BELT__L,
    BeltType::__L => BELT___L,
    BeltType::D_ => BELT_D_,
    BeltType::DL_ => BELT_DL_,
    BeltType::D_L => BELT_D_L,
    BeltType::D__L => BELT_D__L,
    BeltType::_D => BELT__D,
    BeltType::L_D => BELT_L_D,
    BeltType::_DL => BELT__DL,
    BeltType::_D_L => BELT__D_L,
    BeltType::__D => BELT___D,
    BeltType::L__D => BELT_L__D,
    BeltType::_L_D => BELT__L_D,
    BeltType::__DL => BELT___DL,
    BeltType::R_ => BELT_R_,
    BeltType::LR_ => BELT_LR_,
    BeltType::R_L => BELT_R_L,
    BeltType::R__L => BELT_R__L,
    BeltType::DR_ => BELT_DR_,
    BeltType::DLR_ => BELT_DLR_,
    BeltType::DR_L => BELT_DR_L,
    BeltType::DR__L => BELT_DR__L,
    BeltType::R_D => BELT_R_D,
    BeltType::LR_D => BELT_LR_D,
    BeltType::R_DL => BELT_R_DL,
    BeltType::R_D_L => BELT_R_D_L,
    BeltType::R__D => BELT_R__D,
    BeltType::LR__D => BELT_LR__D,
    BeltType::R_L_D => BELT_R_L_D,
    BeltType::R__DL => BELT_R__DL,
    BeltType::_R => BELT__R,
    BeltType::L_R => BELT_L_R,
    BeltType::_LR => BELT__LR,
    BeltType::_R_L => BELT__R_L,
    BeltType::D_R => BELT_D_R,
    BeltType::DL_R => BELT_DL_R,
    BeltType::D_LR => BELT_D_LR,
    BeltType::D_R_L => BELT_D_R_L,
    BeltType::_DR => BELT__DR,
    BeltType::L_DR => BELT_L_DR,
    BeltType::_DLR => BELT__DLR,
    BeltType::_DR_L => BELT__DR_L,
    BeltType::_R_D => BELT__R_D,
    BeltType::L_R_D => BELT_L_R_D,
    BeltType::_LR_D => BELT__LR_D,
    BeltType::_R_DL => BELT__R_DL,
    BeltType::__R => BELT___R,
    BeltType::L__R => BELT_L__R,
    BeltType::_L_R => BELT__L_R,
    BeltType::__LR => BELT___LR,
    BeltType::D__R => BELT_D__R,
    BeltType::DL__R => BELT_DL__R,
    BeltType::D_L_R => BELT_D_L_R,
    BeltType::D__LR => BELT_D__LR,
    BeltType::_D_R => BELT__D_R,
    BeltType::L_D_R => BELT_L_D_R,
    BeltType::_DL_R => BELT__DL_R,
    BeltType::_D_LR => BELT__D_LR,
    BeltType::__DR => BELT___DR,
    BeltType::L__DR => BELT_L__DR,
    BeltType::_L_DR => BELT__L_DR,
    BeltType::__DLR => BELT___DLR,
    BeltType::U_ => BELT_U_,
    BeltType::LU_ => BELT_LU_,
    BeltType::U_L => BELT_U_L,
    BeltType::U__L => BELT_U__L,
    BeltType::DU_ => BELT_DU_,
    BeltType::DLU_ => BELT_DLU_,
    BeltType::DU_L => BELT_DU_L,
    BeltType::DU__L => BELT_DU__L,
    BeltType::U_D => BELT_U_D,
    BeltType::LU_D => BELT_LU_D,
    BeltType::U_DL => BELT_U_DL,
    BeltType::U_D_L => BELT_U_D_L,
    BeltType::U__D => BELT_U__D,
    BeltType::LU__D => BELT_LU__D,
    BeltType::U_L_D => BELT_U_L_D,
    BeltType::U__DL => BELT_U__DL,
    BeltType::RU_ => BELT_RU_,
    BeltType::LRU_ => BELT_LRU_,
    BeltType::RU_L => BELT_RU_L,
    BeltType::RU__L => BELT_RU__L,
    BeltType::DRU_ => BELT_DRU_,
    BeltType::DLRU_ => BELT_DLRU_,
    BeltType::DRU_L => BELT_DRU_L,
    BeltType::DRU__L => BELT_DRU__L,
    BeltType::RU_D => BELT_RU_D,
    BeltType::LRU_D => BELT_LRU_D,
    BeltType::RU_DL => BELT_RU_DL,
    BeltType::RU_D_L => BELT_RU_D_L,
    BeltType::RU__D => BELT_RU__D,
    BeltType::LRU__D => BELT_LRU__D,
    BeltType::RU_L_D => BELT_RU_L_D,
    BeltType::RU__DL => BELT_RU__DL,
    BeltType::U_R => BELT_U_R,
    BeltType::LU_R => BELT_LU_R,
    BeltType::U_LR => BELT_U_LR,
    BeltType::U_R_L => BELT_U_R_L,
    BeltType::DU_R => BELT_DU_R,
    BeltType::DLU_R => BELT_DLU_R,
    BeltType::DU_LR => BELT_DU_LR,
    BeltType::DU_R_L => BELT_DU_R_L,
    BeltType::U_DR => BELT_U_DR,
    BeltType::LU_DR => BELT_LU_DR,
    BeltType::U_DLR => BELT_U_DLR,
    BeltType::U_DR_L => BELT_U_DR_L,
    BeltType::U_R_D => BELT_U_R_D,
    BeltType::LU_R_D => BELT_LU_R_D,
    BeltType::U_LR_D => BELT_U_LR_D,
    BeltType::U_R_DL => BELT_U_R_DL,
    BeltType::U__R => BELT_U__R,
    BeltType::LU__R => BELT_LU__R,
    BeltType::U_L_R => BELT_U_L_R,
    BeltType::U__LR => BELT_U__LR,
    BeltType::DU__R => BELT_DU__R,
    BeltType::DLU__R => BELT_DLU__R,
    BeltType::DU_L_R => BELT_DU_L_R,
    BeltType::DU__LR => BELT_DU__LR,
    BeltType::U_D_R => BELT_U_D_R,
    BeltType::LU_D_R => BELT_LU_D_R,
    BeltType::U_DL_R => BELT_U_DL_R,
    BeltType::U_D_LR => BELT_U_D_LR,
    BeltType::U__DR => BELT_U__DR,
    BeltType::LU__DR => BELT_LU__DR,
    BeltType::U_L_DR => BELT_U_L_DR,
    BeltType::U__DLR => BELT_U__DLR,
    BeltType::_U => BELT__U,
    BeltType::L_U => BELT_L_U,
    BeltType::_LU => BELT__LU,
    BeltType::_U_L => BELT__U_L,
    BeltType::D_U => BELT_D_U,
    BeltType::DL_U => BELT_DL_U,
    BeltType::D_LU => BELT_D_LU,
    BeltType::D_U_L => BELT_D_U_L,
    BeltType::_DU => BELT__DU,
    BeltType::L_DU => BELT_L_DU,
    BeltType::_DLU => BELT__DLU,
    BeltType::_DU_L => BELT__DU_L,
    BeltType::_U_D => BELT__U_D,
    BeltType::L_U_D => BELT_L_U_D,
    BeltType::_LU_D => BELT__LU_D,
    BeltType::_U_DL => BELT__U_DL,
    BeltType::R_U => BELT_R_U,
    BeltType::LR_U => BELT_LR_U,
    BeltType::R_LU => BELT_R_LU,
    BeltType::R_U_L => BELT_R_U_L,
    BeltType::DR_U => BELT_DR_U,
    BeltType::DLR_U => BELT_DLR_U,
    BeltType::DR_LU => BELT_DR_LU,
    BeltType::DR_U_L => BELT_DR_U_L,
    BeltType::R_DU => BELT_R_DU,
    BeltType::LR_DU => BELT_LR_DU,
    BeltType::R_DLU => BELT_R_DLU,
    BeltType::R_DU_L => BELT_R_DU_L,
    BeltType::R_U_D => BELT_R_U_D,
    BeltType::LR_U_D => BELT_LR_U_D,
    BeltType::R_LU_D => BELT_R_LU_D,
    BeltType::R_U_DL => BELT_R_U_DL,
    BeltType::_RU => BELT__RU,
    BeltType::L_RU => BELT_L_RU,
    BeltType::_LRU => BELT__LRU,
    BeltType::_RU_L => BELT__RU_L,
    BeltType::D_RU => BELT_D_RU,
    BeltType::DL_RU => BELT_DL_RU,
    BeltType::D_LRU => BELT_D_LRU,
    BeltType::D_RU_L => BELT_D_RU_L,
    BeltType::_DRU => BELT__DRU,
    BeltType::L_DRU => BELT_L_DRU,
    BeltType::_DLRU => BELT__DLRU,
    BeltType::_DRU_L => BELT__DRU_L,
    BeltType::_RU_D => BELT__RU_D,
    BeltType::L_RU_D => BELT_L_RU_D,
    BeltType::_LRU_D => BELT__LRU_D,
    BeltType::_RU_DL => BELT__RU_DL,
    BeltType::_U_R => BELT__U_R,
    BeltType::L_U_R => BELT_L_U_R,
    BeltType::_LU_R => BELT__LU_R,
    BeltType::_U_LR => BELT__U_LR,
    BeltType::D_U_R => BELT_D_U_R,
    BeltType::DL_U_R => BELT_DL_U_R,
    BeltType::D_LU_R => BELT_D_LU_R,
    BeltType::D_U_LR => BELT_D_U_LR,
    BeltType::_DU_R => BELT__DU_R,
    BeltType::L_DU_R => BELT_L_DU_R,
    BeltType::_DLU_R => BELT__DLU_R,
    BeltType::_DU_LR => BELT__DU_LR,
    BeltType::_U_DR => BELT__U_DR,
    BeltType::L_U_DR => BELT_L_U_DR,
    BeltType::_LU_DR => BELT__LU_DR,
    BeltType::_U_DLR => BELT__U_DLR,
    BeltType::__U => BELT___U,
    BeltType::L__U => BELT_L__U,
    BeltType::_L_U => BELT__L_U,
    BeltType::__LU => BELT___LU,
    BeltType::D__U => BELT_D__U,
    BeltType::DL__U => BELT_DL__U,
    BeltType::D_L_U => BELT_D_L_U,
    BeltType::D__LU => BELT_D__LU,
    BeltType::_D_U => BELT__D_U,
    BeltType::L_D_U => BELT_L_D_U,
    BeltType::_DL_U => BELT__DL_U,
    BeltType::_D_LU => BELT__D_LU,
    BeltType::__DU => BELT___DU,
    BeltType::L__DU => BELT_L__DU,
    BeltType::_L_DU => BELT__L_DU,
    BeltType::__DLU => BELT___DLU,
    BeltType::R__U => BELT_R__U,
    BeltType::LR__U => BELT_LR__U,
    BeltType::R_L_U => BELT_R_L_U,
    BeltType::R__LU => BELT_R__LU,
    BeltType::DR__U => BELT_DR__U,
    BeltType::DLR__U => BELT_DLR__U,
    BeltType::DR_L_U => BELT_DR_L_U,
    BeltType::DR__LU => BELT_DR__LU,
    BeltType::R_D_U => BELT_R_D_U,
    BeltType::LR_D_U => BELT_LR_D_U,
    BeltType::R_DL_U => BELT_R_DL_U,
    BeltType::R_D_LU => BELT_R_D_LU,
    BeltType::R__DU => BELT_R__DU,
    BeltType::LR__DU => BELT_LR__DU,
    BeltType::R_L_DU => BELT_R_L_DU,
    BeltType::R__DLU => BELT_R__DLU,
    BeltType::_R_U => BELT__R_U,
    BeltType::L_R_U => BELT_L_R_U,
    BeltType::_LR_U => BELT__LR_U,
    BeltType::_R_LU => BELT__R_LU,
    BeltType::D_R_U => BELT_D_R_U,
    BeltType::DL_R_U => BELT_DL_R_U,
    BeltType::D_LR_U => BELT_D_LR_U,
    BeltType::D_R_LU => BELT_D_R_LU,
    BeltType::_DR_U => BELT__DR_U,
    BeltType::L_DR_U => BELT_L_DR_U,
    BeltType::_DLR_U => BELT__DLR_U,
    BeltType::_DR_LU => BELT__DR_LU,
    BeltType::_R_DU => BELT__R_DU,
    BeltType::L_R_DU => BELT_L_R_DU,
    BeltType::_LR_DU => BELT__LR_DU,
    BeltType::_R_DLU => BELT__R_DLU,
    BeltType::__RU => BELT___RU,
    BeltType::L__RU => BELT_L__RU,
    BeltType::_L_RU => BELT__L_RU,
    BeltType::__LRU => BELT___LRU,
    BeltType::D__RU => BELT_D__RU,
    BeltType::DL__RU => BELT_DL__RU,
    BeltType::D_L_RU => BELT_D_L_RU,
    BeltType::D__LRU => BELT_D__LRU,
    BeltType::_D_RU => BELT__D_RU,
    BeltType::L_D_RU => BELT_L_D_RU,
    BeltType::_DL_RU => BELT__DL_RU,
    BeltType::_D_LRU => BELT__D_LRU,
    BeltType::__DRU => BELT___DRU,
    BeltType::L__DRU => BELT_L__DRU,
    BeltType::_L_DRU => BELT__L_DRU,
    BeltType::__DLRU => BELT___DLRU,
  };
}

pub const fn belt_type_from_ports(up: Port, right: Port, down: Port, left: Port) -> BeltType {
  // Each port as four possible states (none, in, out, unknown) and there are four ports so there
  // are 4^4=256 options. The belt code is `{inports}_{out-ports}`, where the ports are single
  // letters and each of the two groups is ordered alphabetically. Examples: `lr_u` or `d_r`

  // JS to generate the strings:
  /*
    let codes = [];
    let ports = ['n', 'i', 'o', 'u'];
    for (const u of ports) {
      for (const r of ports) {
        for (const d of ports) {
          for (const l of ports) {
              let ins = [];
              let outs = [];
              let uus = [];
              if (u === 'i') ins.push('u');
              if (u === 'o') outs.push('u');
              if (u === 'u') uus.push('u');
              if (r === 'i') ins.push('r');
              if (r === 'o') outs.push('r');
              if (r === 'u') uus.push('r');
              if (d === 'i') ins.push('d');
              if (d === 'o') outs.push('d');
              if (d === 'u') uus.push('d');
              if (l === 'i') ins.push('l');
              if (l === 'o') outs.push('l');
              if (l === 'u') uus.push('l');
              codes.push(`${ins.join('')}_${outs.join('')}${uus.length?'_':''}${uus.join('')}`);

              // Generate the code below:
              //                 codes.push(`(Port::${u==='n'?'None':u==='i'?'Inbound':u==='o'?'Outbound':'Unknown'}, Port::${r==='n'?'None':r==='i'?'Inbound':r==='o'?'Outbound':'Unknown'}, Port::${d==='n'?'None':d==='i'?'Inbound':d==='o'?'Outbound':'Unknown'}, Port::${l==='n'?'None':l==='i'?'Inbound':l==='o'?'Outbound':'Unknown'}) => "${ins.join('')}_${outs.join('')}${uus.length?'_':''}${uus.join('')}",`);

          }
        }
      }
    }
    console.log(codes.join('\n'))
  */


  match (up, right, down, left) {
    (Port::None, Port::None, Port::None, Port::None) => BeltType::NONE,
    (Port::None, Port::None, Port::None, Port::Inbound) => BeltType::L_,
    (Port::None, Port::None, Port::None, Port::Outbound) => BeltType::_L,
    (Port::None, Port::None, Port::None, Port::Unknown) => BeltType::__L,
    (Port::None, Port::None, Port::Inbound, Port::None) => BeltType::D_,
    (Port::None, Port::None, Port::Inbound, Port::Inbound) => BeltType::DL_,
    (Port::None, Port::None, Port::Inbound, Port::Outbound) => BeltType::D_L,
    (Port::None, Port::None, Port::Inbound, Port::Unknown) => BeltType::D__L,
    (Port::None, Port::None, Port::Outbound, Port::None) => BeltType::_D,
    (Port::None, Port::None, Port::Outbound, Port::Inbound) => BeltType::L_D,
    (Port::None, Port::None, Port::Outbound, Port::Outbound) => BeltType::_DL,
    (Port::None, Port::None, Port::Outbound, Port::Unknown) => BeltType::_D_L,
    (Port::None, Port::None, Port::Unknown, Port::None) => BeltType::__D,
    (Port::None, Port::None, Port::Unknown, Port::Inbound) => BeltType::L__D,
    (Port::None, Port::None, Port::Unknown, Port::Outbound) => BeltType::_L_D,
    (Port::None, Port::None, Port::Unknown, Port::Unknown) => BeltType::__DL,
    (Port::None, Port::Inbound, Port::None, Port::None) => BeltType::R_,
    (Port::None, Port::Inbound, Port::None, Port::Inbound) => BeltType::LR_,
    (Port::None, Port::Inbound, Port::None, Port::Outbound) => BeltType::R_L,
    (Port::None, Port::Inbound, Port::None, Port::Unknown) => BeltType::R__L,
    (Port::None, Port::Inbound, Port::Inbound, Port::None) => BeltType::DR_,
    (Port::None, Port::Inbound, Port::Inbound, Port::Inbound) => BeltType::DLR_,
    (Port::None, Port::Inbound, Port::Inbound, Port::Outbound) => BeltType::DR_L,
    (Port::None, Port::Inbound, Port::Inbound, Port::Unknown) => BeltType::DR__L,
    (Port::None, Port::Inbound, Port::Outbound, Port::None) => BeltType::R_D,
    (Port::None, Port::Inbound, Port::Outbound, Port::Inbound) => BeltType::LR_D,
    (Port::None, Port::Inbound, Port::Outbound, Port::Outbound) => BeltType::R_DL,
    (Port::None, Port::Inbound, Port::Outbound, Port::Unknown) => BeltType::R_D_L,
    (Port::None, Port::Inbound, Port::Unknown, Port::None) => BeltType::R__D,
    (Port::None, Port::Inbound, Port::Unknown, Port::Inbound) => BeltType::LR__D,
    (Port::None, Port::Inbound, Port::Unknown, Port::Outbound) => BeltType::R_L_D,
    (Port::None, Port::Inbound, Port::Unknown, Port::Unknown) => BeltType::R__DL,
    (Port::None, Port::Outbound, Port::None, Port::None) => BeltType::_R,
    (Port::None, Port::Outbound, Port::None, Port::Inbound) => BeltType::L_R,
    (Port::None, Port::Outbound, Port::None, Port::Outbound) => BeltType::_LR,
    (Port::None, Port::Outbound, Port::None, Port::Unknown) => BeltType::_R_L,
    (Port::None, Port::Outbound, Port::Inbound, Port::None) => BeltType::D_R,
    (Port::None, Port::Outbound, Port::Inbound, Port::Inbound) => BeltType::DL_R,
    (Port::None, Port::Outbound, Port::Inbound, Port::Outbound) => BeltType::D_LR,
    (Port::None, Port::Outbound, Port::Inbound, Port::Unknown) => BeltType::D_R_L,
    (Port::None, Port::Outbound, Port::Outbound, Port::None) => BeltType::_DR,
    (Port::None, Port::Outbound, Port::Outbound, Port::Inbound) => BeltType::L_DR,
    (Port::None, Port::Outbound, Port::Outbound, Port::Outbound) => BeltType::_DLR,
    (Port::None, Port::Outbound, Port::Outbound, Port::Unknown) => BeltType::_DR_L,
    (Port::None, Port::Outbound, Port::Unknown, Port::None) => BeltType::_R_D,
    (Port::None, Port::Outbound, Port::Unknown, Port::Inbound) => BeltType::L_R_D,
    (Port::None, Port::Outbound, Port::Unknown, Port::Outbound) => BeltType::_LR_D,
    (Port::None, Port::Outbound, Port::Unknown, Port::Unknown) => BeltType::_R_DL,
    (Port::None, Port::Unknown, Port::None, Port::None) => BeltType::__R,
    (Port::None, Port::Unknown, Port::None, Port::Inbound) => BeltType::L__R,
    (Port::None, Port::Unknown, Port::None, Port::Outbound) => BeltType::_L_R,
    (Port::None, Port::Unknown, Port::None, Port::Unknown) => BeltType::__LR,
    (Port::None, Port::Unknown, Port::Inbound, Port::None) => BeltType::D__R,
    (Port::None, Port::Unknown, Port::Inbound, Port::Inbound) => BeltType::DL__R,
    (Port::None, Port::Unknown, Port::Inbound, Port::Outbound) => BeltType::D_L_R,
    (Port::None, Port::Unknown, Port::Inbound, Port::Unknown) => BeltType::D__LR,
    (Port::None, Port::Unknown, Port::Outbound, Port::None) => BeltType::_D_R,
    (Port::None, Port::Unknown, Port::Outbound, Port::Inbound) => BeltType::L_D_R,
    (Port::None, Port::Unknown, Port::Outbound, Port::Outbound) => BeltType::_DL_R,
    (Port::None, Port::Unknown, Port::Outbound, Port::Unknown) => BeltType::_D_LR,
    (Port::None, Port::Unknown, Port::Unknown, Port::None) => BeltType::__DR,
    (Port::None, Port::Unknown, Port::Unknown, Port::Inbound) => BeltType::L__DR,
    (Port::None, Port::Unknown, Port::Unknown, Port::Outbound) => BeltType::_L_DR,
    (Port::None, Port::Unknown, Port::Unknown, Port::Unknown) => BeltType::__DLR,
    (Port::Inbound, Port::None, Port::None, Port::None) => BeltType::U_,
    (Port::Inbound, Port::None, Port::None, Port::Inbound) => BeltType::LU_,
    (Port::Inbound, Port::None, Port::None, Port::Outbound) => BeltType::U_L,
    (Port::Inbound, Port::None, Port::None, Port::Unknown) => BeltType::U__L,
    (Port::Inbound, Port::None, Port::Inbound, Port::None) => BeltType::DU_,
    (Port::Inbound, Port::None, Port::Inbound, Port::Inbound) => BeltType::DLU_,
    (Port::Inbound, Port::None, Port::Inbound, Port::Outbound) => BeltType::DU_L,
    (Port::Inbound, Port::None, Port::Inbound, Port::Unknown) => BeltType::DU__L,
    (Port::Inbound, Port::None, Port::Outbound, Port::None) => BeltType::U_D,
    (Port::Inbound, Port::None, Port::Outbound, Port::Inbound) => BeltType::LU_D,
    (Port::Inbound, Port::None, Port::Outbound, Port::Outbound) => BeltType::U_DL,
    (Port::Inbound, Port::None, Port::Outbound, Port::Unknown) => BeltType::U_D_L,
    (Port::Inbound, Port::None, Port::Unknown, Port::None) => BeltType::U__D,
    (Port::Inbound, Port::None, Port::Unknown, Port::Inbound) => BeltType::LU__D,
    (Port::Inbound, Port::None, Port::Unknown, Port::Outbound) => BeltType::U_L_D,
    (Port::Inbound, Port::None, Port::Unknown, Port::Unknown) => BeltType::U__DL,
    (Port::Inbound, Port::Inbound, Port::None, Port::None) => BeltType::RU_,
    (Port::Inbound, Port::Inbound, Port::None, Port::Inbound) => BeltType::LRU_,
    (Port::Inbound, Port::Inbound, Port::None, Port::Outbound) => BeltType::RU_L,
    (Port::Inbound, Port::Inbound, Port::None, Port::Unknown) => BeltType::RU__L,
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::None) => BeltType::DRU_,
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::Inbound) => BeltType::DLRU_,
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::Outbound) => BeltType::DRU_L,
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::Unknown) => BeltType::DRU__L,
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::None) => BeltType::RU_D,
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::Inbound) => BeltType::LRU_D,
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::Outbound) => BeltType::RU_DL,
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::Unknown) => BeltType::RU_D_L,
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::None) => BeltType::RU__D,
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::Inbound) => BeltType::LRU__D,
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::Outbound) => BeltType::RU_L_D,
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::Unknown) => BeltType::RU__DL,
    (Port::Inbound, Port::Outbound, Port::None, Port::None) => BeltType::U_R,
    (Port::Inbound, Port::Outbound, Port::None, Port::Inbound) => BeltType::LU_R,
    (Port::Inbound, Port::Outbound, Port::None, Port::Outbound) => BeltType::U_LR,
    (Port::Inbound, Port::Outbound, Port::None, Port::Unknown) => BeltType::U_R_L,
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::None) => BeltType::DU_R,
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::Inbound) => BeltType::DLU_R,
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::Outbound) => BeltType::DU_LR,
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::Unknown) => BeltType::DU_R_L,
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::None) => BeltType::U_DR,
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::Inbound) => BeltType::LU_DR,
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::Outbound) => BeltType::U_DLR,
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::Unknown) => BeltType::U_DR_L,
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::None) => BeltType::U_R_D,
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::Inbound) => BeltType::LU_R_D,
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::Outbound) => BeltType::U_LR_D,
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::Unknown) => BeltType::U_R_DL,
    (Port::Inbound, Port::Unknown, Port::None, Port::None) => BeltType::U__R,
    (Port::Inbound, Port::Unknown, Port::None, Port::Inbound) => BeltType::LU__R,
    (Port::Inbound, Port::Unknown, Port::None, Port::Outbound) => BeltType::U_L_R,
    (Port::Inbound, Port::Unknown, Port::None, Port::Unknown) => BeltType::U__LR,
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::None) => BeltType::DU__R,
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::Inbound) => BeltType::DLU__R,
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::Outbound) => BeltType::DU_L_R,
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::Unknown) => BeltType::DU__LR,
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::None) => BeltType::U_D_R,
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::Inbound) => BeltType::LU_D_R,
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::Outbound) => BeltType::U_DL_R,
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::Unknown) => BeltType::U_D_LR,
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::None) => BeltType::U__DR,
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::Inbound) => BeltType::LU__DR,
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::Outbound) => BeltType::U_L_DR,
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::Unknown) => BeltType::U__DLR,
    (Port::Outbound, Port::None, Port::None, Port::None) => BeltType::_U,
    (Port::Outbound, Port::None, Port::None, Port::Inbound) => BeltType::L_U,
    (Port::Outbound, Port::None, Port::None, Port::Outbound) => BeltType::_LU,
    (Port::Outbound, Port::None, Port::None, Port::Unknown) => BeltType::_U_L,
    (Port::Outbound, Port::None, Port::Inbound, Port::None) => BeltType::D_U,
    (Port::Outbound, Port::None, Port::Inbound, Port::Inbound) => BeltType::DL_U,
    (Port::Outbound, Port::None, Port::Inbound, Port::Outbound) => BeltType::D_LU,
    (Port::Outbound, Port::None, Port::Inbound, Port::Unknown) => BeltType::D_U_L,
    (Port::Outbound, Port::None, Port::Outbound, Port::None) => BeltType::_DU,
    (Port::Outbound, Port::None, Port::Outbound, Port::Inbound) => BeltType::L_DU,
    (Port::Outbound, Port::None, Port::Outbound, Port::Outbound) => BeltType::_DLU,
    (Port::Outbound, Port::None, Port::Outbound, Port::Unknown) => BeltType::_DU_L,
    (Port::Outbound, Port::None, Port::Unknown, Port::None) => BeltType::_U_D,
    (Port::Outbound, Port::None, Port::Unknown, Port::Inbound) => BeltType::L_U_D,
    (Port::Outbound, Port::None, Port::Unknown, Port::Outbound) => BeltType::_LU_D,
    (Port::Outbound, Port::None, Port::Unknown, Port::Unknown) => BeltType::_U_DL,
    (Port::Outbound, Port::Inbound, Port::None, Port::None) => BeltType::R_U,
    (Port::Outbound, Port::Inbound, Port::None, Port::Inbound) => BeltType::LR_U,
    (Port::Outbound, Port::Inbound, Port::None, Port::Outbound) => BeltType::R_LU,
    (Port::Outbound, Port::Inbound, Port::None, Port::Unknown) => BeltType::R_U_L,
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::None) => BeltType::DR_U,
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::Inbound) => BeltType::DLR_U,
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::Outbound) => BeltType::DR_LU,
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::Unknown) => BeltType::DR_U_L,
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::None) => BeltType::R_DU,
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::Inbound) => BeltType::LR_DU,
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::Outbound) => BeltType::R_DLU,
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::Unknown) => BeltType::R_DU_L,
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::None) => BeltType::R_U_D,
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::Inbound) => BeltType::LR_U_D,
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::Outbound) => BeltType::R_LU_D,
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::Unknown) => BeltType::R_U_DL,
    (Port::Outbound, Port::Outbound, Port::None, Port::None) => BeltType::_RU,
    (Port::Outbound, Port::Outbound, Port::None, Port::Inbound) => BeltType::L_RU,
    (Port::Outbound, Port::Outbound, Port::None, Port::Outbound) => BeltType::_LRU,
    (Port::Outbound, Port::Outbound, Port::None, Port::Unknown) => BeltType::_RU_L,
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::None) => BeltType::D_RU,
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::Inbound) => BeltType::DL_RU,
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::Outbound) => BeltType::D_LRU,
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::Unknown) => BeltType::D_RU_L,
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::None) => BeltType::_DRU,
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Inbound) => BeltType::L_DRU,
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Outbound) => BeltType::_DLRU,
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Unknown) => BeltType::_DRU_L,
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::None) => BeltType::_RU_D,
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::Inbound) => BeltType::L_RU_D,
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::Outbound) => BeltType::_LRU_D,
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::Unknown) => BeltType::_RU_DL,
    (Port::Outbound, Port::Unknown, Port::None, Port::None) => BeltType::_U_R,
    (Port::Outbound, Port::Unknown, Port::None, Port::Inbound) => BeltType::L_U_R,
    (Port::Outbound, Port::Unknown, Port::None, Port::Outbound) => BeltType::_LU_R,
    (Port::Outbound, Port::Unknown, Port::None, Port::Unknown) => BeltType::_U_LR,
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::None) => BeltType::D_U_R,
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::Inbound) => BeltType::DL_U_R,
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::Outbound) => BeltType::D_LU_R,
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::Unknown) => BeltType::D_U_LR,
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::None) => BeltType::_DU_R,
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::Inbound) => BeltType::L_DU_R,
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::Outbound) => BeltType::_DLU_R,
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::Unknown) => BeltType::_DU_LR,
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::None) => BeltType::_U_DR,
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::Inbound) => BeltType::L_U_DR,
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::Outbound) => BeltType::_LU_DR,
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::Unknown) => BeltType::_U_DLR,
    (Port::Unknown, Port::None, Port::None, Port::None) => BeltType::__U,
    (Port::Unknown, Port::None, Port::None, Port::Inbound) => BeltType::L__U,
    (Port::Unknown, Port::None, Port::None, Port::Outbound) => BeltType::_L_U,
    (Port::Unknown, Port::None, Port::None, Port::Unknown) => BeltType::__LU,
    (Port::Unknown, Port::None, Port::Inbound, Port::None) => BeltType::D__U,
    (Port::Unknown, Port::None, Port::Inbound, Port::Inbound) => BeltType::DL__U,
    (Port::Unknown, Port::None, Port::Inbound, Port::Outbound) => BeltType::D_L_U,
    (Port::Unknown, Port::None, Port::Inbound, Port::Unknown) => BeltType::D__LU,
    (Port::Unknown, Port::None, Port::Outbound, Port::None) => BeltType::_D_U,
    (Port::Unknown, Port::None, Port::Outbound, Port::Inbound) => BeltType::L_D_U,
    (Port::Unknown, Port::None, Port::Outbound, Port::Outbound) => BeltType::_DL_U,
    (Port::Unknown, Port::None, Port::Outbound, Port::Unknown) => BeltType::_D_LU,
    (Port::Unknown, Port::None, Port::Unknown, Port::None) => BeltType::__DU,
    (Port::Unknown, Port::None, Port::Unknown, Port::Inbound) => BeltType::L__DU,
    (Port::Unknown, Port::None, Port::Unknown, Port::Outbound) => BeltType::_L_DU,
    (Port::Unknown, Port::None, Port::Unknown, Port::Unknown) => BeltType::__DLU,
    (Port::Unknown, Port::Inbound, Port::None, Port::None) => BeltType::R__U,
    (Port::Unknown, Port::Inbound, Port::None, Port::Inbound) => BeltType::LR__U,
    (Port::Unknown, Port::Inbound, Port::None, Port::Outbound) => BeltType::R_L_U,
    (Port::Unknown, Port::Inbound, Port::None, Port::Unknown) => BeltType::R__LU,
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::None) => BeltType::DR__U,
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::Inbound) => BeltType::DLR__U,
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::Outbound) => BeltType::DR_L_U,
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::Unknown) => BeltType::DR__LU,
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::None) => BeltType::R_D_U,
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::Inbound) => BeltType::LR_D_U,
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::Outbound) => BeltType::R_DL_U,
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::Unknown) => BeltType::R_D_LU,
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::None) => BeltType::R__DU,
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::Inbound) => BeltType::LR__DU,
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::Outbound) => BeltType::R_L_DU,
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::Unknown) => BeltType::R__DLU,
    (Port::Unknown, Port::Outbound, Port::None, Port::None) => BeltType::_R_U,
    (Port::Unknown, Port::Outbound, Port::None, Port::Inbound) => BeltType::L_R_U,
    (Port::Unknown, Port::Outbound, Port::None, Port::Outbound) => BeltType::_LR_U,
    (Port::Unknown, Port::Outbound, Port::None, Port::Unknown) => BeltType::_R_LU,
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::None) => BeltType::D_R_U,
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::Inbound) => BeltType::DL_R_U,
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::Outbound) => BeltType::D_LR_U,
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::Unknown) => BeltType::D_R_LU,
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::None) => BeltType::_DR_U,
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::Inbound) => BeltType::L_DR_U,
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::Outbound) => BeltType::_DLR_U,
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::Unknown) => BeltType::_DR_LU,
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::None) => BeltType::_R_DU,
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::Inbound) => BeltType::L_R_DU,
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::Outbound) => BeltType::_LR_DU,
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::Unknown) => BeltType::_R_DLU,
    (Port::Unknown, Port::Unknown, Port::None, Port::None) => BeltType::__RU,
    (Port::Unknown, Port::Unknown, Port::None, Port::Inbound) => BeltType::L__RU,
    (Port::Unknown, Port::Unknown, Port::None, Port::Outbound) => BeltType::_L_RU,
    (Port::Unknown, Port::Unknown, Port::None, Port::Unknown) => BeltType::__LRU,
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::None) => BeltType::D__RU,
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::Inbound) => BeltType::DL__RU,
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::Outbound) => BeltType::D_L_RU,
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::Unknown) => BeltType::D__LRU,
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::None) => BeltType::_D_RU,
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::Inbound) => BeltType::L_D_RU,
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::Outbound) => BeltType::_DL_RU,
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::Unknown) => BeltType::_D_LRU,
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::None) => BeltType::__DRU,
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::Inbound) => BeltType::L__DRU,
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::Outbound) => BeltType::_L_DRU,
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::Unknown) => BeltType::__DLRU,
  }
}

pub fn belt_index_to_belt_type(index: usize) -> BeltType {
  let t = BELT_TYPES_NOT_INDEXABLE_BY_TYPE_BUT_BY_CODE_POS[index];
  assert_eq!(t as usize, index, "index should map to a belt type with the same index value");
  return t;
}

pub fn belt_name_to_belt_type(code: &str) -> BeltType {
  let pos = BELT_CODES.iter().position(|&s| s == code);

  return match pos {
    Some(pos) => BELT_TYPES_NOT_INDEXABLE_BY_TYPE_BUT_BY_CODE_POS[pos - BeltType::NONE as usize], // TODO: unhappy about the sub but it'll have to do for now
    None => panic!("Belt code {} was not found in the belt name list", code),
  };
}
