use std::borrow::Borrow;
use std::convert::TryInto;

use super::belt::*;
use super::belt_type::*;
use super::belt_type::*;
use super::cell::*;
use super::config::*;
use super::demand::*;
use super::direction::*;
use super::factory::*;
use super::floor::*;
use super::machine::*;
use super::options::*;
use super::part::*;
use super::state::*;
use super::supply::*;
use super::utils::*;

#[derive(PartialEq, Debug, Copy, Clone)]
pub enum Port {
  Inbound,
  Outbound,
  None,
  Unknown,
}

pub fn port_disconnect_cells(options: &Options, state: &State, config: &Config, factory: &mut Factory, coord1: usize, dir1: Direction, coord2: usize, dir2: Direction) {
  // Note: this still requires fixing the cell meta and a new factory prio
  port_disconnect_cell(options, state, config, factory, coord1, dir1);
  port_disconnect_cell(options, state, config, factory, coord2, dir2);
}
pub fn port_disconnect_cell(options: &Options, state: &State, config: &Config, factory: &mut Factory, coord: usize, dir: Direction) {
  // Some cells have fixed ports, only belts are dynamic, machines reset to unknown
  // Note: this still requires fixing the cell meta and a new factory prio

  if factory.floor[coord].kind == CellKind::Belt || factory.floor[coord].kind == CellKind::Machine {
    match dir {
      Direction::Up => cell_set_port_u_to(options, state, config, factory, coord, Port::None, to_coord_up(coord)),
      Direction::Right => cell_set_port_r_to(options, state, config, factory, coord, Port::None, to_coord_right(coord)),
      Direction::Down => cell_set_port_d_to(options, state, config, factory, coord, Port::None, to_coord_down(coord)),
      Direction::Left => cell_set_port_l_to(options, state, config, factory, coord, Port::None, to_coord_left(coord)),
    }
  }

  belt_receive_part(factory, coord, Direction::Up, part_none(config));
}

pub fn serialize_ports(factory: &Factory, coord: usize) -> String {
  return format!("ports @{}:  {:?}  {:?}  {:?}  {:?}", coord, factory.floor[coord].port_u, factory.floor[coord].port_r, factory.floor[coord].port_d, factory.floor[coord].port_l);
}

pub fn port_count(factory: &Factory, coord: usize) -> u8 {
  return
    if factory.floor[coord].port_u != Port::None { 1 } else { 0 } +
    if factory.floor[coord].port_r != Port::None { 1 } else { 0 } +
    if factory.floor[coord].port_d != Port::None { 1 } else { 0 } +
    if factory.floor[coord].port_l != Port::None { 1 } else { 0 };
}

pub fn port_to_char(port: Port) -> char {
  return match port {
    Port::Inbound => { 'i' },
    Port::Outbound => { 'o' },
    Port::Unknown => { '?' },
    Port::None => { '-' },
  };
}

/*
// https://en.wikipedia.org/wiki/Box-drawing_character
fn ports_to_cell_icon(up: Port, right: Port, down: Port, left: Port) -> char {
  // Each port as four possible states (none, in, out, unknown) and there are four ports so there
  // are 4^4=256 options. Luckily ascii delivers.
  // empty: none
  // in: thin
  // out: thick
  // unknown: double, except when there is no double for that case, then use the T with double
  match (up, right, down, left) {
    (Port::None, Port::None, Port::None, Port::None) => ' ',
    (Port::None, Port::None, Port::None, Port::Inbound) => '╴',
    (Port::None, Port::None, Port::None, Port::Outbound) => '╸',
    (Port::None, Port::None, Port::None, Port::Unknown) => '╡', // There is no "just-left" double char
    (Port::None, Port::None, Port::Inbound, Port::None) => '╷',
    (Port::None, Port::None, Port::Inbound, Port::Inbound) => '┐',
    (Port::None, Port::None, Port::Inbound, Port::Outbound) => '┑',
    (Port::None, Port::None, Port::Inbound, Port::Unknown) => '╕',
    (Port::None, Port::None, Port::Outbound, Port::None) => ' ',
    (Port::None, Port::None, Port::Outbound, Port::Inbound) => ' ',
    (Port::None, Port::None, Port::Outbound, Port::Outbound) => ' ',
    (Port::None, Port::None, Port::Outbound, Port::Unknown) => ' ',
    (Port::None, Port::None, Port::Unknown, Port::None) => ' ',
    (Port::None, Port::None, Port::Unknown, Port::Inbound) => ' ',
    (Port::None, Port::None, Port::Unknown, Port::Outbound) => ' ',
    (Port::None, Port::None, Port::Unknown, Port::Unknown) => ' ',
    (Port::None, Port::Inbound, Port::None, Port::None) => ' ',
    (Port::None, Port::Inbound, Port::None, Port::Inbound) => ' ',
    (Port::None, Port::Inbound, Port::None, Port::Outbound) => ' ',
    (Port::None, Port::Inbound, Port::None, Port::Unknown) => ' ',
    (Port::None, Port::Inbound, Port::Inbound, Port::None) => ' ',
    (Port::None, Port::Inbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::None, Port::Inbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::None, Port::Inbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::None, Port::Inbound, Port::Outbound, Port::None) => ' ',
    (Port::None, Port::Inbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::None, Port::Inbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::None, Port::Inbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::None, Port::Inbound, Port::Unknown, Port::None) => ' ',
    (Port::None, Port::Inbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::None, Port::Inbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::None, Port::Inbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::None, Port::Outbound, Port::None, Port::None) => ' ',
    (Port::None, Port::Outbound, Port::None, Port::Inbound) => ' ',
    (Port::None, Port::Outbound, Port::None, Port::Outbound) => ' ',
    (Port::None, Port::Outbound, Port::None, Port::Unknown) => ' ',
    (Port::None, Port::Outbound, Port::Inbound, Port::None) => ' ',
    (Port::None, Port::Outbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::None, Port::Outbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::None, Port::Outbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::None, Port::Outbound, Port::Outbound, Port::None) => ' ',
    (Port::None, Port::Outbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::None, Port::Outbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::None, Port::Outbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::None, Port::Outbound, Port::Unknown, Port::None) => ' ',
    (Port::None, Port::Outbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::None, Port::Outbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::None, Port::Outbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::None, Port::Unknown, Port::None, Port::None) => ' ',
    (Port::None, Port::Unknown, Port::None, Port::Inbound) => ' ',
    (Port::None, Port::Unknown, Port::None, Port::Outbound) => ' ',
    (Port::None, Port::Unknown, Port::None, Port::Unknown) => ' ',
    (Port::None, Port::Unknown, Port::Inbound, Port::None) => ' ',
    (Port::None, Port::Unknown, Port::Inbound, Port::Inbound) => ' ',
    (Port::None, Port::Unknown, Port::Inbound, Port::Outbound) => ' ',
    (Port::None, Port::Unknown, Port::Inbound, Port::Unknown) => ' ',
    (Port::None, Port::Unknown, Port::Outbound, Port::None) => ' ',
    (Port::None, Port::Unknown, Port::Outbound, Port::Inbound) => ' ',
    (Port::None, Port::Unknown, Port::Outbound, Port::Outbound) => ' ',
    (Port::None, Port::Unknown, Port::Outbound, Port::Unknown) => ' ',
    (Port::None, Port::Unknown, Port::Unknown, Port::None) => ' ',
    (Port::None, Port::Unknown, Port::Unknown, Port::Inbound) => ' ',
    (Port::None, Port::Unknown, Port::Unknown, Port::Outbound) => ' ',
    (Port::None, Port::Unknown, Port::Unknown, Port::Unknown) => ' ',
    (Port::Inbound, Port::None, Port::None, Port::None) => ' ',
    (Port::Inbound, Port::None, Port::None, Port::Inbound) => ' ',
    (Port::Inbound, Port::None, Port::None, Port::Outbound) => ' ',
    (Port::Inbound, Port::None, Port::None, Port::Unknown) => ' ',
    (Port::Inbound, Port::None, Port::Inbound, Port::None) => ' ',
    (Port::Inbound, Port::None, Port::Inbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::None, Port::Inbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::None, Port::Inbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::None, Port::Outbound, Port::None) => ' ',
    (Port::Inbound, Port::None, Port::Outbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::None, Port::Outbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::None, Port::Outbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::None, Port::Unknown, Port::None) => ' ',
    (Port::Inbound, Port::None, Port::Unknown, Port::Inbound) => ' ',
    (Port::Inbound, Port::None, Port::Unknown, Port::Outbound) => ' ',
    (Port::Inbound, Port::None, Port::Unknown, Port::Unknown) => ' ',
    (Port::Inbound, Port::Inbound, Port::None, Port::None) => ' ',
    (Port::Inbound, Port::Inbound, Port::None, Port::Inbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::None, Port::Outbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::None, Port::Unknown) => ' ',
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::None) => ' ',
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::None) => ' ',
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::None) => ' ',
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::Inbound, Port::Inbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::Inbound, Port::Outbound, Port::None, Port::None) => ' ',
    (Port::Inbound, Port::Outbound, Port::None, Port::Inbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::None, Port::Outbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::None, Port::Unknown) => ' ',
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::None) => ' ',
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::None) => ' ',
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::None) => ' ',
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::Inbound, Port::Outbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::Inbound, Port::Unknown, Port::None, Port::None) => ' ',
    (Port::Inbound, Port::Unknown, Port::None, Port::Inbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::None, Port::Outbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::None, Port::Unknown) => ' ',
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::None) => ' ',
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::Inbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::None) => ' ',
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::Inbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::Outbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::Outbound, Port::Unknown) => ' ',
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::None) => ' ',
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::Inbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::Outbound) => ' ',
    (Port::Inbound, Port::Unknown, Port::Unknown, Port::Unknown) => ' ',
    (Port::Outbound, Port::None, Port::None, Port::None) => ' ',
    (Port::Outbound, Port::None, Port::None, Port::Inbound) => ' ',
    (Port::Outbound, Port::None, Port::None, Port::Outbound) => ' ',
    (Port::Outbound, Port::None, Port::None, Port::Unknown) => ' ',
    (Port::Outbound, Port::None, Port::Inbound, Port::None) => ' ',
    (Port::Outbound, Port::None, Port::Inbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::None, Port::Inbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::None, Port::Inbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::None, Port::Outbound, Port::None) => ' ',
    (Port::Outbound, Port::None, Port::Outbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::None, Port::Outbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::None, Port::Outbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::None, Port::Unknown, Port::None) => ' ',
    (Port::Outbound, Port::None, Port::Unknown, Port::Inbound) => ' ',
    (Port::Outbound, Port::None, Port::Unknown, Port::Outbound) => ' ',
    (Port::Outbound, Port::None, Port::Unknown, Port::Unknown) => ' ',
    (Port::Outbound, Port::Inbound, Port::None, Port::None) => ' ',
    (Port::Outbound, Port::Inbound, Port::None, Port::Inbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::None, Port::Outbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::None, Port::Unknown) => ' ',
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::None) => ' ',
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::None) => ' ',
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::None) => ' ',
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::Outbound, Port::Inbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::Outbound, Port::Outbound, Port::None, Port::None) => ' ',
    (Port::Outbound, Port::Outbound, Port::None, Port::Inbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::None, Port::Outbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::None, Port::Unknown) => ' ',
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::None) => ' ',
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::None) => ' ',
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::None) => ' ',
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::Outbound, Port::Outbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::Outbound, Port::Unknown, Port::None, Port::None) => ' ',
    (Port::Outbound, Port::Unknown, Port::None, Port::Inbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::None, Port::Outbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::None, Port::Unknown) => ' ',
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::None) => ' ',
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::Inbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::None) => ' ',
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::Inbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::Outbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::Outbound, Port::Unknown) => ' ',
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::None) => ' ',
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::Inbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::Outbound) => ' ',
    (Port::Outbound, Port::Unknown, Port::Unknown, Port::Unknown) => ' ',
    (Port::Unknown, Port::None, Port::None, Port::None) => ' ',
    (Port::Unknown, Port::None, Port::None, Port::Inbound) => ' ',
    (Port::Unknown, Port::None, Port::None, Port::Outbound) => ' ',
    (Port::Unknown, Port::None, Port::None, Port::Unknown) => ' ',
    (Port::Unknown, Port::None, Port::Inbound, Port::None) => ' ',
    (Port::Unknown, Port::None, Port::Inbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::None, Port::Inbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::None, Port::Inbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::None, Port::Outbound, Port::None) => ' ',
    (Port::Unknown, Port::None, Port::Outbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::None, Port::Outbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::None, Port::Outbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::None, Port::Unknown, Port::None) => ' ',
    (Port::Unknown, Port::None, Port::Unknown, Port::Inbound) => ' ',
    (Port::Unknown, Port::None, Port::Unknown, Port::Outbound) => ' ',
    (Port::Unknown, Port::None, Port::Unknown, Port::Unknown) => ' ',
    (Port::Unknown, Port::Inbound, Port::None, Port::None) => ' ',
    (Port::Unknown, Port::Inbound, Port::None, Port::Inbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::None, Port::Outbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::None, Port::Unknown) => ' ',
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::None) => ' ',
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::None) => ' ',
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::None) => ' ',
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::Unknown, Port::Inbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::Unknown, Port::Outbound, Port::None, Port::None) => ' ',
    (Port::Unknown, Port::Outbound, Port::None, Port::Inbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::None, Port::Outbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::None, Port::Unknown) => ' ',
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::None) => ' ',
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::Inbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::None) => ' ',
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::Outbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::None) => ' ',
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::Inbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::Outbound) => ' ',
    (Port::Unknown, Port::Outbound, Port::Unknown, Port::Unknown) => ' ',
    (Port::Unknown, Port::Unknown, Port::None, Port::None) => ' ',
    (Port::Unknown, Port::Unknown, Port::None, Port::Inbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::None, Port::Outbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::None, Port::Unknown) => ' ',
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::None) => ' ',
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::Inbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::None) => ' ',
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::Inbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::Outbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::Outbound, Port::Unknown) => ' ',
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::None) => ' ',
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::Inbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::Outbound) => ' ',
    (Port::Unknown, Port::Unknown, Port::Unknown, Port::Unknown) => ' ',
  }
}
 */

/*
pub fn ports_to_cell_belt(up: Port, right: Port, down: Port, left: Port) -> BeltMeta {
  match   (up,          right,          down,           left) {
    (Port::Inbound,  Port::Inbound,  Port::Inbound,  Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::Inbound,  Port::Inbound,  Port::Inbound,  Port::Outbound) =>  CELL_BELT_DRU_L,
    (Port::Inbound,  Port::Inbound,  Port::Inbound,  Port::None) =>      CELL_BELT_INVALID,
    (Port::Inbound,  Port::Inbound,  Port::Outbound, Port::Inbound) =>   CELL_BELT_LRU_D,
    (Port::Inbound,  Port::Inbound,  Port::Outbound, Port::Outbound) =>  CELL_BELT_RU_DL,
    (Port::Inbound,  Port::Inbound,  Port::Outbound, Port::None) =>      CELL_BELT_RU_D,
    (Port::Inbound,  Port::Inbound,  Port::None,     Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::Inbound,  Port::Inbound,  Port::None,     Port::Outbound) =>  CELL_BELT_RU_L,
    (Port::Inbound,  Port::Inbound,  Port::None,     Port::None) =>      CELL_BELT_INVALID,
    (Port::Inbound,  Port::Outbound, Port::Inbound,  Port::Inbound) =>   CELL_BELT_DLU_R,
    (Port::Inbound,  Port::Outbound, Port::Inbound,  Port::Outbound) =>  CELL_BELT_DU_LR,
    (Port::Inbound,  Port::Outbound, Port::Inbound,  Port::None) =>      CELL_BELT_DU_R,
    (Port::Inbound,  Port::Outbound, Port::Outbound, Port::Inbound) =>   CELL_BELT_LU_DR,
    (Port::Inbound,  Port::Outbound, Port::Outbound, Port::Outbound) =>  CELL_BELT_U_DLR,
    (Port::Inbound,  Port::Outbound, Port::Outbound, Port::None) =>      CELL_BELT_U_DR,
    (Port::Inbound,  Port::Outbound, Port::None,     Port::Inbound) =>   CELL_BELT_LU_R,
    (Port::Inbound,  Port::Outbound, Port::None,     Port::Outbound) =>  CELL_BELT_U_LR,
    (Port::Inbound,  Port::Outbound, Port::None,     Port::None) =>      CELL_BELT_U_R,
    (Port::Inbound,  Port::None,     Port::Inbound,  Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::Inbound,  Port::None,     Port::Inbound,  Port::Outbound) =>  CELL_BELT_DU_L,
    (Port::Inbound,  Port::None,     Port::Inbound,  Port::None) =>      CELL_BELT_INVALID,
    (Port::Inbound,  Port::None,     Port::Outbound, Port::Inbound) =>   CELL_BELT_LU_D,
    (Port::Inbound,  Port::None,     Port::Outbound, Port::Outbound) =>  CELL_BELT_U_DL,
    (Port::Inbound,  Port::None,     Port::Outbound, Port::None) =>      CELL_BELT_U_D,
    (Port::Inbound,  Port::None,     Port::None,     Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::Inbound,  Port::None,     Port::None,     Port::Outbound) =>  CELL_BELT_U_L,
    (Port::Inbound,  Port::None,     Port::None,     Port::None) =>      CELL_BELT_INVALID,
    (Port::Outbound, Port::Inbound,  Port::Inbound,  Port::Inbound) =>   CELL_BELT_DLR_U,
    (Port::Outbound, Port::Inbound,  Port::Inbound,  Port::Outbound) =>  CELL_BELT_DR_LU,
    (Port::Outbound, Port::Inbound,  Port::Inbound,  Port::None) =>      CELL_BELT_DR_U,
    (Port::Outbound, Port::Inbound,  Port::Outbound, Port::Inbound) =>   CELL_BELT_LR_DU,
    (Port::Outbound, Port::Inbound,  Port::Outbound, Port::Outbound) =>  CELL_BELT_R_DLU,
    (Port::Outbound, Port::Inbound,  Port::Outbound, Port::None) =>      CELL_BELT_R_DU,
    (Port::Outbound, Port::Inbound,  Port::None,     Port::Inbound) =>   CELL_BELT_LR_U,
    (Port::Outbound, Port::Inbound,  Port::None,     Port::Outbound) =>  CELL_BELT_R_LU,
    (Port::Outbound, Port::Inbound,  Port::None,     Port::None) =>      CELL_BELT_R_U,
    (Port::Outbound, Port::Outbound, Port::Inbound,  Port::Inbound) =>   CELL_BELT_DL_RU,
    (Port::Outbound, Port::Outbound, Port::Inbound,  Port::Outbound) =>  CELL_BELT_D_LRU,
    (Port::Outbound, Port::Outbound, Port::Inbound,  Port::None) =>      CELL_BELT_D_RU,
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Inbound) =>   CELL_BELT_L_DRU,
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::Outbound, Port::Outbound, Port::Outbound, Port::None) =>      CELL_BELT_INVALID,
    (Port::Outbound, Port::Outbound, Port::None,     Port::Inbound) =>   CELL_BELT_L_RU,
    (Port::Outbound, Port::Outbound, Port::None,     Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::Outbound, Port::Outbound, Port::None,     Port::None) =>      CELL_BELT_INVALID,
    (Port::Outbound, Port::None,     Port::Inbound,  Port::Inbound) =>   CELL_BELT_DL_U,
    (Port::Outbound, Port::None,     Port::Inbound,  Port::Outbound) =>  CELL_BELT_D_LU,
    (Port::Outbound, Port::None,     Port::Inbound,  Port::None) =>      CELL_BELT_D_U,
    (Port::Outbound, Port::None,     Port::Outbound, Port::Inbound) =>   CELL_BELT_L_DU,
    (Port::Outbound, Port::None,     Port::Outbound, Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::Outbound, Port::None,     Port::Outbound, Port::None) =>      CELL_BELT_INVALID,
    (Port::Outbound, Port::None,     Port::None,     Port::Inbound) =>   CELL_BELT_L_U,
    (Port::Outbound, Port::None,     Port::None,     Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::Outbound, Port::None,     Port::None,     Port::None) =>      CELL_BELT_INVALID,
    (Port::None,     Port::Inbound,  Port::Inbound,  Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::None,     Port::Inbound,  Port::Inbound,  Port::Outbound) =>  CELL_BELT_DR_L,
    (Port::None,     Port::Inbound,  Port::Inbound,  Port::None) =>      CELL_BELT_INVALID,
    (Port::None,     Port::Inbound,  Port::Outbound, Port::Inbound) =>   CELL_BELT_LR_D,
    (Port::None,     Port::Inbound,  Port::Outbound, Port::Outbound) =>  CELL_BELT_R_DL,
    (Port::None,     Port::Inbound,  Port::Outbound, Port::None) =>      CELL_BELT_R_D,
    (Port::None,     Port::Inbound,  Port::None,     Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::None,     Port::Inbound,  Port::None,     Port::Outbound) =>  CELL_BELT_R_L,
    (Port::None,     Port::Inbound,  Port::None,     Port::None) =>      CELL_BELT_INVALID,
    (Port::None,     Port::Outbound, Port::Inbound,  Port::Inbound) =>   CELL_BELT_DL_R,
    (Port::None,     Port::Outbound, Port::Inbound,  Port::Outbound) =>  CELL_BELT_D_LR,
    (Port::None,     Port::Outbound, Port::Inbound,  Port::None) =>      CELL_BELT_D_R,
    (Port::None,     Port::Outbound, Port::Outbound, Port::Inbound) =>   CELL_BELT_L_DR,
    (Port::None,     Port::Outbound, Port::Outbound, Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::None,     Port::Outbound, Port::Outbound, Port::None) =>      CELL_BELT_INVALID,
    (Port::None,     Port::Outbound, Port::None,     Port::Inbound) =>   CELL_BELT_L_R,
    (Port::None,     Port::Outbound, Port::None,     Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::None,     Port::Outbound, Port::None,     Port::None) =>      CELL_BELT_INVALID,
    (Port::None,     Port::None,     Port::Inbound,  Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::None,     Port::None,     Port::Inbound,  Port::Outbound) =>  CELL_BELT_D_L,
    (Port::None,     Port::None,     Port::Inbound,  Port::None) =>      CELL_BELT_INVALID,
    (Port::None,     Port::None,     Port::Outbound, Port::Inbound) =>   CELL_BELT_L_D,
    (Port::None,     Port::None,     Port::Outbound, Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::None,     Port::None,     Port::Outbound, Port::None) =>      CELL_BELT_INVALID,
    (Port::None,     Port::None,     Port::None,     Port::Inbound) =>   CELL_BELT_INVALID,
    (Port::None,     Port::None,     Port::None,     Port::Outbound) =>  CELL_BELT_INVALID,
    (Port::None,     Port::None,     Port::None,     Port::None) =>      CELL_BELT_INVALID,
  }
}
*/
